# Generated by Django 3.0.2 on 2020-02-09 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('contact', models.CharField(max_length=20)),
                ('date_created', models.DateField()),
                ('client_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date_created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ImportExportEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_description', models.CharField(max_length=200)),
                ('total_stock_available', models.IntegerField()),
                ('is_returned', models.BooleanField()),
                ('expense', models.IntegerField()),
                ('product_import', models.IntegerField()),
                ('product_export', models.IntegerField()),
                ('total_imported', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('remaining_products', models.IntegerField()),
                ('date_created', models.DateField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Company')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Product')),
            ],
        ),
    ]
