version: 2

jobs:

  build:

    working_directory: ~/LBM

    docker:

      - image: circleci/python:3.6.6

    steps:

      - checkout

      - run: sudo chown -R circleci:circleci /usr/local/bin

      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages

      - run: make python_requirements

      - run: make test-quality